add lifecycle to worker

diff --git a/base/concourse/worker/statefulset.yaml b/base/concourse/worker/statefulset.yaml
--- a/base/concourse/worker/statefulset.yaml
+++ b/base/concourse/worker/statefulset.yaml
@@ -20,10 +20,49 @@ spec:
         - name: concourse-worker
           image: "concourse/concourse:4.2.2"
           imagePullPolicy: IfNotPresent
+          command:
+            - /bin/sh
           args:
-            - worker
-            - |
-              --name=${HOSTNAME}
+            - -c
+            - |-
+              cp /dev/null /tmp/.liveness_prove
+              rm -rf ${CONCOURSE_WORKER_DIR}
+              while ! concourse retire-worker --name=${HOSTNAME} | grep -q worker-not-found; do
+                touch /tmp/.pre_start_cleanup
+                sleep 5
+              done
+              rm -f /tmp/.pre_start_cleanup
+              concourse worker --name=${HOSTNAME} | tee -a /tmp/.liveness_prove
+          livenessProbe:
+            exec:
+              command:
+                - /bin/sh
+                - -c
+                - |-
+                  FATAL_ERRORS=$( echo "{LIVENESS_PROBE_FATAL_ERRORS}" | grep -q '\S' && \
+                    grep -F "${LIVENESS_PROBE_FATAL_ERRORS}" /tmp/.liveness_probe )
+                  cp /dev/null /tmp/.liveness_probe
+                  if [ ! -z "${FATAL_ERRORS}" ]; then
+                    >&2 echo "Fatal error detected: ${FATAL_ERRORS}"
+                    exit 1
+                  fi
+                  if [ -f /tmp/.pre_start_cleanup ]; then
+                    >&2 echo "Still trying to clean up before starting concourse. 'fly prune-worker -w ${HOSTNAME}' might need to be called to force cleanup."
+                    exit 1
+                  fi
+            failureThreshold: 1
+            initialDelaySeconds: 10
+            periodSeconds: 10
+          lifecycle:
+            preStop:
+              exec:
+                command:
+                  - /bin/sh
+                  - -c
+                  - |-
+                    while ! concourse retire-worker --name=${HOSTNAME} | grep -q worker-not-found; do
+                      sleep 5
+                    done
           env:
             - name: CONCOURSE_WORK_DIR
               value: "/concourse-work-dir"
@@ -54,7 +93,8 @@ spec:
               value: $(CONCOURSE_LOG_LEVEL)
             - name: CONCOURSE_BAGGAGECLAIM_LOG_LEVEL
               value: $(CONCOURSE_LOG_LEVEL)
-            
+            - name: LIVENESS_PROBE_FATAL_ERRORS
+              value: "guardian.api.garden-server.create.failed\nbaggageclaim.api.volume-server.create-volume-async.failed-to-create"
           resources:
             requests:
               cpu: 100m
